version: '3'
services:
  client:
    build:
      context: ./my-app
      dockerfile: .docker/client/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      context: ./my-app
      dockerfile: .docker/server/Dockerfile
    ports:
      - 3001:3001
