version: '3'
services:
  client:
    image: maxog/client-1:latest
    volumes:
      - ../client:/app
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    image: maxog/server-1:latest

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
