version: '3'
services:
  client:
    image: maxog/client-1:latest
    volumes:
      - ../client:/app
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    image: maxog/server-1:latest
    ports:
      - 3001:3001
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    depends_on:
      - client
      - server
