version: '3'
services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    volumes:
      - ../client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - server
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
